import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Get notification email from settings
    const { data: settings } = await supabaseAdmin.from("site_settings").select("value").eq("key", "notification_email").single();
    const toEmail = settings?.value || "contact.terraria@gmail.com";

    // Get date range for last month
    const now = new Date();
    const firstOfThisMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    const firstOfLastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
    const from = firstOfLastMonth.toISOString();
    const to = firstOfThisMonth.toISOString();
    const monthName = firstOfLastMonth.toLocaleString("en", { month: "long", year: "numeric" });

    // Fetch bookings & orders for last month
    const [bookingsRes, ordersRes] = await Promise.all([
      supabaseAdmin.from("bookings").select("*").gte("created_at", from).lt("created_at", to),
      supabaseAdmin.from("orders").select("*").gte("created_at", from).lt("created_at", to),
    ]);

    const bookings = bookingsRes.data || [];
    const orders = ordersRes.data || [];

    const totalRevenue = orders.reduce((sum: number, o: any) => sum + (o.grand_total || 0), 0);
    const pendingBookings = bookings.filter((b: any) => b.status === "pending").length;
    const confirmedBookings = bookings.filter((b: any) => b.status === "confirmed").length;
    const pendingOrders = orders.filter((o: any) => o.status === "pending").length;
    const completedOrders = orders.filter((o: any) => o.status === "done" || o.status === "delivered").length;

    const emailBody = `
      <h1 style="font-family:sans-serif;color:#333;">📊 Monthly Report — ${monthName}</h1>
      <table style="border-collapse:collapse;font-family:sans-serif;width:100%;max-width:500px;">
        <tr style="background:#f5f0eb;"><td colspan="2" style="padding:12px;font-weight:bold;font-size:16px;">📅 Bookings (${bookings.length})</td></tr>
        <tr><td style="padding:8px 12px;">Pending</td><td style="padding:8px 12px;font-weight:bold;">${pendingBookings}</td></tr>
        <tr><td style="padding:8px 12px;">Confirmed</td><td style="padding:8px 12px;font-weight:bold;">${confirmedBookings}</td></tr>
        <tr><td style="padding:8px 12px;">Others</td><td style="padding:8px 12px;font-weight:bold;">${bookings.length - pendingBookings - confirmedBookings}</td></tr>
        <tr style="background:#f5f0eb;"><td colspan="2" style="padding:12px;font-weight:bold;font-size:16px;">🛒 Orders (${orders.length})</td></tr>
        <tr><td style="padding:8px 12px;">Pending</td><td style="padding:8px 12px;font-weight:bold;">${pendingOrders}</td></tr>
        <tr><td style="padding:8px 12px;">Completed</td><td style="padding:8px 12px;font-weight:bold;">${completedOrders}</td></tr>
        <tr><td style="padding:8px 12px;">Total Revenue</td><td style="padding:8px 12px;font-weight:bold;color:#e65100;">${totalRevenue} DH</td></tr>
      </table>
      <p style="font-family:sans-serif;color:#888;margin-top:20px;font-size:12px;">Auto-generated by Terraria Workshops</p>
    `;

    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "Terraria <onboarding@resend.dev>",
        to: [toEmail],
        subject: `📊 Monthly Report — ${monthName} | Terraria`,
        html: emailBody,
      }),
    });

    console.log(`Monthly report sent for ${monthName}`);

    return new Response(JSON.stringify({ success: true, month: monthName }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Monthly report error:", error);
    return new Response(JSON.stringify({ error: "Failed to generate report" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
