// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-workshops.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_workshops_default = defineTool({
  name: "list_workshops",
  title: "List workshops",
  description: "List Terraria Workshops experiences (pottery, zellij, embroidery, carpets, etc.) with their base pricing per city.",
  inputSchema: {
    city: z.string().optional().describe("Optional city slug or name to filter pricing (e.g. 'tetouan').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data: cities, error: e1 } = await supabase.from("workshop_cities").select("id, slug, name");
    if (e1) return { content: [{ type: "text", text: e1.message }], isError: true };
    const { data: pricing, error: e2 } = await supabase.from("workshop_city_pricing").select("workshop_slug, city_id, price, currency, duration_minutes");
    if (e2) return { content: [{ type: "text", text: e2.message }], isError: true };
    const cityMap = new Map((cities ?? []).map((c) => [c.id, c]));
    const filtered = (pricing ?? []).filter((p) => {
      if (!city) return true;
      const c = cityMap.get(p.city_id);
      return c && (c.slug === city.toLowerCase() || c.name?.toLowerCase() === city.toLowerCase());
    });
    const rows = filtered.map((p) => ({
      workshop: p.workshop_slug,
      city: cityMap.get(p.city_id)?.name ?? null,
      price: p.price,
      currency: p.currency,
      duration_minutes: p.duration_minutes
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { workshops: rows }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_blog_posts_default = defineTool2({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog posts from Terraria Workshops with title, slug, and excerpt.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max posts to return (default 10)."),
    category: z2.string().optional().describe("Optional category filter (e.g. 'zellige').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("blog_posts").select("slug, title, excerpt, category, published_at").eq("is_published", true).order("published_at", { ascending: false }).limit(limit ?? 10);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_products_default = defineTool3({
  name: "list_store_products",
  title: "List store products",
  description: "List handmade products available in the Terraria Workshops online store.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max products (default 20)."),
    section: z3.string().optional().describe("Optional store section slug filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, section }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("products").select("id, name, description, price, currency, section, image_url, in_stock").limit(limit ?? 20);
    if (section) query = query.eq("section", section);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/check-availability.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var check_availability_default = defineTool4({
  name: "check_workshop_availability",
  title: "Check workshop availability",
  description: "Check upcoming available time slots for a Terraria workshop between two dates. Returns date, time, and remaining capacity per slot.",
  inputSchema: {
    workshop_slug: z4.string().describe("Workshop slug (e.g. 'pottery-experience', 'zellij', 'handbuilding')."),
    from_date: z4.string().describe("Start date, ISO format YYYY-MM-DD."),
    to_date: z4.string().describe("End date, ISO format YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workshop_slug, from_date, to_date }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.rpc("get_terraria_availability", {
      p_workshop_slug: workshop_slug,
      p_from_date: from_date,
      p_to_date: to_date
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { slots: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "terraria-workshops-mcp",
  title: "Terraria Workshops MCP",
  version: "0.1.0",
  instructions: "Tools for exploring Terraria Workshops: list handcraft workshops and pricing, check availability of upcoming sessions, browse the online store, and read the blog.",
  tools: [list_workshops_default, check_availability_default, list_blog_posts_default, list_products_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
